### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker-server#1]
Hello thank you

after doing the instructions I have this message
![image](https://cloud.githubusercontent.com/assets/15144026/20349181/75eb8bac-ac09-11e6-8566-cc08eaf42d55.png)

IIS 8.5 windows 2012r2 / php 5.6.19 /

**Comment by tomolimo** [comment]
Which instructions?
Did you follow the wiki, even if not yet finished? https://github.com/tomolimo/processmaker-server/wiki

**Comment by satyan01** [comment]
yes

**Comment by satyan01** [comment]
installed on iis with /workflow/public_html folder
php 5.6.19
when I go to the webpage error 500 and message above

**Comment by tomolimo** [comment]
Anyway, it says 'access denied', then solve it :)

**Comment by satyan01** [comment]
Failed opening required 'C:/gulliver/system/class.bootstrap.php'  

I don't have this folder

**Comment by tomolimo** [comment]
I believe you have not defined correctly the web site

**Comment by satyan01** [comment]
same conf as glpi

**Comment by tomolimo** [comment]
please follow the wiki and the links I've posted in it, the configuration is not the same than GLPi

**Comment by satyan01** [comment]
Open the downloaded archive, and extract it onto the desired folder - DONE
Configure your web server to point to the /workflow/public_html folder - DONE 
PHP should already be installed and configured for your web server, I will not detail this point as so many tutorials already exist for that. Pay attention to the version that must be used for ProcessMaker (check the ProcessMaker official wiki). Currently my own configuration is PHP 5.6.25 - 5.6.19 OK

**Comment by satyan01** [comment]
http://localhost/pm/sys/en/neoclassic/login/login 

ERROR 500

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/20349537/2f32b8b4-ac0b-11e6-8baa-4612b2ae0b40.png)

**Comment by satyan01** [comment]
it works with 8080 port locally

**Comment by satyan01** [comment]
it stays on checking...

**Comment by satyan01** [comment]
Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 1097 Notice: Only variables should be assigned by reference in C:\inetpub\wwwroot\pm\gulliver\system\class.headPublisher.php on line 767

**Comment by satyan01** [comment]
I can click on next until license agreement 

I can't click or go down to accept the request

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/20350567/b415b942-ac0f-11e6-9ccd-770f336ac3be.png)

**Comment by tomolimo** [comment]
The installation of ProcessMaker server is really straightforward if you follow the instructions from the the wiki sites (one from here, and one from PM itself). 
So please review them in details. 
Especially because currently I don't have time to help you deeper with this. 
As I said : the wiki is not finished. 
Thank you 
Tomolimo

**Comment by satyan01** [comment]
I have opened a ticket on process maker forum, it looks like an issue from process maker

**Comment by tomolimo** [comment]
Hello Satyan01,
Could you re-try with latest version of processmaker-server: [here](https://github.com/tomolimo/processmaker-server/releases/latest)?
thank you
regards,
Tomolimo
