### ISSUE TITLE
Nginx processmaker-server installation error

### ISSUE THREAD

**Issue by shahmilan34** [tomolimo/processmaker-server#13]
installed processmaker-server Release 3.0.1.8-RE-1.8 . Configured nginx processmaker from reference https://github.com/tomolimo/processmaker-server/wiki/Nginx. Then installed db from  processmaker-server frontend and typed ./processmaker workspace-upgrade command but after installing processmaker redirects http://172.17.0.3/sys/en/neoclassic/login/login  and blank screen comes.

errors:
no errors in /var/log/nginx/errror.log and /var/log/php-fpm/error.log

nginx configuration:
server {
    listen       80;
    server_name  172.17.0.3;
    root         /opt/processmaker/workflow/public_html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /var/www/html;
    }

    # Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    rewrite ^/.*/(.*)$ /glpi/app.php last;

    location ~ [^/]\.php(/|$) {
            # regex to split $uri to $fastcgi_script_name and $fastcgi_path
            fastcgi_split_path_info ^(.+\.php)(/.+)$;

            # Check that the PHP script exists before passing it
            try_files $fastcgi_script_name =404;

            fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
	    fastcgi_read_timeout 600;	    

            include fastcgi.conf;

            # Bypass the fact that try_files resets $fastcgi_path_info
            # # see: http://trac.nginx.org/nginx/ticket/321
            set $path_info $fastcgi_path_info;
            fastcgi_param PATH_INFO $path_info;

            # allow directory index
            fastcgi_index index.php;
     }

}

**Comment by tomolimo** [comment]
Hello @shahmilan34 

I don't understand why you did this command: 

>  ./processmaker workspace-upgrade

?

Thank you
Regards,
Tomolimo

**Comment by shahmilan34** [comment]
To address issue mentioned in below link
https://forum.processmaker.com/viewtopic.php?t=707492

**Comment by tomolimo** [comment]
Hello
I'm sorry but I cannot help you on this topic, as I don't know nginx.
For information I never used the upgrade command for a new instance of the server. 
As I never get the behavior mentioned in the forum. 

Regards 
Tomolimo

**Comment by tomolimo** [comment]
Any feedback on this issue?

**Comment by tomolimo** [comment]
As I got now news, I close, but feel free to re-open if you need.
