### ISSUE TITLE
Migration to 3.3.0 official release

### ISSUE THREAD

**Issue by tomolimo** [tomolimo/processmaker-server#15]
Migration to 3.3.0 official release

**Comment by rohit-ambre-uno** [comment]
Is this version stable as you haven't made a Release for the same?
so even I would like to contribute and test new release.

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 
Let me check if I made some new modifications since this commit
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno,

This version is OK for tests and should be compatible with the plugin.
Here is a short notice on how to upgrade:

1. Set PM plugin under maintenance mode		
1. stop pm web site
1. backup
	processmaker folder			
	mysql database			
1. upgrade
	copy 'ProcessMaker 3.3.0 - RE 1.0' source code over pm current web site
	mysql db set sql_mode			clear sql_mode (PM server is not compatible with mysql STRICT mode)
	php -f processmaker upgrade
	mysql db set sql_mode			set sql_mode										
1. start pm web site					
1. Assign permissions to roles to PROCESSMAKER_ADMIN assign available permissions			PM_UNCANCELCASE, PM_REST_API_APPLICATIONS, PM_REASSIGNCASE_SUPERVISOR
1. Reset PM plugin maintenance mode					
1. test from GLPI web site
		ProcessMaker plugin settings			
		PM plugin process synchro			
		PM plugin process tasks synchro			
		PM case listing			
		...			

Regards,
Tomolimo
