### ISSUE TITLE
 [wrapped: Could not execute query [Native Error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'wf_workflow.APP_CACHE_VIEW.DEL_INDEX' 

### ISSUE THREAD

**Issue by iamaer4fa** [tomolimo/processmaker-server#16]
It seems I have this issue in Ubuntu 16.04 VM running your processmaker-server forked for glpi plugin.

This installation is new and I created or imported my process from my other processmaker install.\
I downloaded glpi 9.2 as required, install it on the same domain with your processmaker-server modified version.

I click on participated and it shows this error box. Also, I created a test case in order for me to have a participated case, and the same error occurs. Please see whole error message below:

[wrapped: Could not execute query [Native Error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'wf_workflow.APP_CACHE_VIEW.DEL_INDEX' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by] [User Info: SELECT APP_CACHE_VIEW.APP_UID, APP_CACHE_VIEW.DEL_INDEX, APP_CACHE_VIEW.DEL_LAST_INDEX, APP_CACHE_VIEW.APP_NUMBER, APP_CACHE_VIEW.APP_STATUS, APP_CACHE_VIEW.USR_UID, APP_CACHE_VIEW.PREVIOUS_USR_UID, APP_CACHE_VIEW.TAS_UID, APP_CACHE_VIEW.PRO_UID, APP_CACHE_VIEW.DEL_DELEGATE_DATE, APP_CACHE_VIEW.DEL_INIT_DATE, APP_CACHE_VIEW.DEL_FINISH_DATE, APP_CACHE_VIEW.DEL_TASK_DUE_DATE, APP_CACHE_VIEW.DEL_RISK_DATE, APP_CACHE_VIEW.DEL_THREAD_STATUS, APP_CACHE_VIEW.APP_THREAD_STATUS, APP_CACHE_VIEW.APP_TITLE, APP_CACHE_VIEW.APP_PRO_TITLE, APP_CACHE_VIEW.APP_TAS_TITLE, APP_CACHE_VIEW.APP_CURRENT_USER, APP_CACHE_VIEW.APP_DEL_PREVIOUS_USER, APP_CACHE_VIEW.DEL_PRIORITY, APP_CACHE_VIEW.DEL_DURATION, APP_CACHE_VIEW.DEL_QUEUE_DURATION, APP_CACHE_VIEW.DEL_DELAY_DURATION, APP_CACHE_VIEW.DEL_STARTED, APP_CACHE_VIEW.DEL_FINISHED, APP_CACHE_VIEW.DEL_DELAYED, APP_CACHE_VIEW.APP_CREATE_DATE, APP_CACHE_VIEW.APP_FINISH_DATE, APP_CACHE_VIEW.APP_UPDATE_DATE, APP_CACHE_VIEW.APP_OVERDUE_PERCENTAGE, APP_CACHE_VIEW.DEL_INIT_DATE, APP_CACHE_VIEW.TAS_UID, APP_CACHE_VIEW.PRO_UID, CU.USR_UID AS USR_UID, CU.USR_FIRSTNAME AS USR_FIRSTNAME, CU.USR_LASTNAME AS USR_LASTNAME, CU.USR_USERNAME AS USR_USERNAME, (SELECT CON_VALUE FROM CONTENT WHERE CON_ID = APPDELCR.TAS_UID AND CON_LANG = 'en' AND CON_CATEGORY = 'TAS_TITLE') AS APPDELCR_APP_TAS_TITLE, USRCR.USR_UID AS USRCR_USR_UID, USRCR.USR_FIRSTNAME AS USRCR_USR_FIRSTNAME, USRCR.USR_LASTNAME AS USRCR_USR_LASTNAME, USRCR.USR_USERNAME AS USRCR_USR_USERNAME, PU.USR_FIRSTNAME AS PREVIOUS_USR_FIRSTNAME, PU.USR_LASTNAME AS PREVIOUS_USR_LASTNAME, PU.USR_USERNAME AS PREVIOUS_USR_USERNAME FROM APP_CACHE_VIEW LEFT JOIN TASK ON (APP_CACHE_VIEW.TAS_UID=TASK.TAS_UID) LEFT JOIN USERS CU ON (APP_CACHE_VIEW.USR_UID=CU.USR_UID) LEFT JOIN USERS PU ON (APP_CACHE_VIEW.PREVIOUS_USR_UID=PU.USR_UID) LEFT JOIN APP_DELEGATION APPDELCR ON (APP_CACHE_VIEW.APP_UID=APPDELCR.APP_UID AND APPDELCR.DEL_LAST_INDEX=1) LEFT JOIN USERS USRCR ON (APPDELCR.USR_UID=USRCR.USR_UID) WHERE APP_CACHE_VIEW.USR_UID='00000000000000000000000000000001' AND TASK.TAS_TYPE NOT IN ('WEBENTRYEVENT','END-MESSAGE-EVENT','START-MESSAGE-EVENT','INTERMEDIATE-THROW-MESSAGE-EVENT','INTERMEDIATE-CATCH-MESSAGE-EVENT') GROUP BY APP_CACHE_VIEW.APP_UID ORDER BY APP_CACHE_VIEW.APP_NUMBER DESC LIMIT 25]]

![processmaker-glpi-error](https://user-images.githubusercontent.com/8325058/57171505-82efd580-6e47-11e9-8e77-04d3ed4a3cc5.jpg)

**Comment by tomolimo** [comment]
Hello @allanregistos,
 
Even if you are using my forked version of PM, you have to respect the requirements like explained here:  https://wiki.processmaker.com/3.3/ProcessMaker_Installation_Requirements#Software_Requirements
Look at this line:

> Database
> --
> MySQL | 5.6.x | If planning to connect to external databases, install the client software and/or PHP modules for Oracle, SQL Server or PostgreSQL.Warning: ONLY_FULL_GROUP_BY mode is not supported.
> 

Thank you,
Regards,
Tomolimo

**Comment by iamaer4fa** [comment]
Ah my bad. Thank you for pointing this out
