### ISSUE TITLE
You tried to start a new case without send the USER UID or TASK UID

### ISSUE THREAD

**Issue by kopnyaevtm88** [tomolimo/processmaker-server#17]
Good day!
Help me!
Problem adding to glpi Process case!
log:
Error creating case!
You tried to start a new case without send the USER UID or TASK UID! (100)
GLPI v 9.4.3
Process maker v 3.3.10
Automatic job completed pm

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/64356304-502f3700-d00b-11e9-83c3-99010309d457.png)

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/64356347-650bca80-d00b-11e9-8b6d-5f04f96583e3.png)

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/64356463-97b5c300-d00b-11e9-99ee-fef8f0162d48.png)

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88,

This error means that you have not assigned users to the first task of the process.
Did you read the wiki?
See: https://github.com/tomolimo/processmaker/wiki
And this: https://github.com/tomolimo/processmaker-server/wiki
And, especially, did you followed the tutorials?

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88 

Any news for your PM installation?

**Comment by kopnyaevtm88** [comment]
Hello!

I checked everything according to the instructions, everything is fine. Error same

![image](https://user-images.githubusercontent.com/54949945/65948869-bc069300-e443-11e9-8860-e6ea767f615f.png)
![image](https://user-images.githubusercontent.com/54949945/65948896-cd4f9f80-e443-11e9-9019-fd39134f1963.png)
![image](https://user-images.githubusercontent.com/54949945/65948918-d8a2cb00-e443-11e9-8113-94de2c9d943c.png)
![image](https://user-images.githubusercontent.com/54949945/65948950-e8221400-e443-11e9-81d2-1db9dbf194a9.png)
![image](https://user-images.githubusercontent.com/54949945/65948966-f3753f80-e443-11e9-8c5f-b1800aedb2e1.png)
![image](https://user-images.githubusercontent.com/54949945/65949000-08ea6980-e444-11e9-840b-e23e1e908e61.
![image](https://user-images.githubusercontent.com/54949945/65949019-11db3b00-e444-11e9-96e5-3c5618e76dcf.png)

**Comment by kopnyaevtm88** [comment]
Maybe there is a video on how to configure this plugin and server?

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88 
There is no video: just the wiki which is usually enough...
Could you remind me the version of PM server you have installed?
Thank you
Regards,
Tomolimo

**Comment by kopnyaevtm88** [comment]
GLPI v 9.4.3
Process maker v 3.3.10
Automatic job completed pm

**Comment by tomolimo** [comment]
hello @kopnyaevtm88 
I'm sorry, but you have not followed the wiki: the version of PM server you have installed is not yet supported by the plugin. See:  [PM server](https://github.com/tomolimo/processmaker-server/wiki) 
Thank you to re-installed a supported release as mentioned in the wiki.
Regards,
Tomolimo

**Comment by kopnyaevtm88** [comment]
Добрый день!
Поставил версию  сервера
![image](https://user-images.githubusercontent.com/54949945/66318888-d699aa00-e924-11e9-9944-6368844ef188.png)
Create skins 
![image](https://user-images.githubusercontent.com/54949945/66318931-ec0ed400-e924-11e9-87fb-936478548f5a.png)
Create precess
![image](https://user-images.githubusercontent.com/54949945/66319001-05178500-e925-11e9-9cf2-8231f9d9ff4b.png)
Create group GLPI_USER
![image](https://user-images.githubusercontent.com/54949945/66319069-1e203600-e925-11e9-82ad-c2412647d7e7.png)

Connection setup
![image](https://user-images.githubusercontent.com/54949945/66319256-79522880-e925-11e9-8690-7531b4e81b47.png)

processes are visible
![image](https://user-images.githubusercontent.com/54949945/66319309-9129ac80-e925-11e9-8e48-881ff6ea6e87.png)

The error is the same when applying
![image](https://user-images.githubusercontent.com/54949945/66319402-bc140080-e925-11e9-84d6-3f9f07ed40ba.png)
![image](https://user-images.githubusercontent.com/54949945/66319432-c635ff00-e925-11e9-9394-37c12712604d.png)

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88 
This usually means that either there is no assigned users to the first task or either that GLPI users are not synchronized with PM users or it can also mean that your current user in GLPI doens't have the right to start the first task.
Could you check these?
Thank you
Regards,
Tomolimo

**Comment by kopnyaevtm88** [comment]
I am a super user in GLPI

**Comment by kopnyaevtm88** [comment]
there is no information in my task
![image](https://user-images.githubusercontent.com/54949945/66320725-09916d00-e928-11e9-8c85-3db1af120a40.png)

**Comment by kopnyaevtm88** [comment]
You have no thoughts?

**Comment by tomolimo** [comment]
Hello,
Could you check in the PHP error log files?
Thank you,
Regards,
Tomolimo

**Comment by kopnyaevtm88** [comment]
in glpi ?

**Comment by tomolimo** [comment]
yes, please

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/66376722-ee227280-e9b8-11e9-9276-c18929ca03e9.png)
that's all there is in glpi

**Comment by kopnyaevtm88** [comment]
Let me throw you all the settings, what did I do?

**Comment by tomolimo** [comment]
@kopnyaevtm88 you've posted the Apache logs, but what I requested is the PHP error logs that must be in glpi/files/_log/  folder

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/66376886-380b5880-e9b9-11e9-8a8b-00b2aee4561f.png)
![image](https://user-images.githubusercontent.com/54949945/66376946-55402700-e9b9-11e9-8b4e-ea34a76c20c2.png)
![image](https://user-images.githubusercontent.com/54949945/66376982-61c47f80-e9b9-11e9-9e56-63e11fc64c27.png)
![image](https://user-images.githubusercontent.com/54949945/66377065-7ef94e00-e9b9-11e9-98da-b76b7462aea1.png)
![image](https://user-images.githubusercontent.com/54949945/66377599-95ec7000-e9ba-11e9-9d1d-97562c18f445.png)
![image](https://user-images.githubusercontent.com/54949945/66377631-a866a980-e9ba-11e9-98d5-53b8250d8c9a.png)
![image](https://user-images.githubusercontent.com/54949945/66377685-c16f5a80-e9ba-11e9-9a3f-97fff5b2a72a.png)

**Comment by kopnyaevtm88** [comment]
these are all my settings

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88,
Question: did you try to 'synchronize tasks' of the TEST process?
Thank you,
Regards,
Tomolimo

**Comment by kopnyaevtm88** [comment]
Yes
![image](https://user-images.githubusercontent.com/54949945/66384179-f5e91380-e9c6-11e9-9d89-9d4c7985d227.png)

**Comment by tomolimo** [comment]
Hello @kopnyaevtm88 
This will synchronize the process list, but not the task list of the TEST process. 
To synchronize task list, you must edit a process and click on the 'Synchronize tasks' button

**Comment by kopnyaevtm88** [comment]
in processmaker ?

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/66384896-3e550100-e9c8-11e9-826f-065ef10ff246.png)

**Comment by tomolimo** [comment]
in GLPI, just click on the TEST process name, to access the process edit form, see here: https://github.com/tomolimo/processmaker/wiki/Process-configuration#task-list

**Comment by tomolimo** [comment]
Moreover, you MUST follow the wiki:
Here: https://github.com/tomolimo/processmaker-server/wiki
and here: https://github.com/tomolimo/processmaker/wiki

**Comment by kopnyaevtm88** [comment]
For some reason, it's empty for me.
![image](https://user-images.githubusercontent.com/54949945/66385643-8294d100-e9c9-11e9-95ef-784439c05a33.png)

**Comment by tomolimo** [comment]
Please check the PHP error logs file: you should have an error in it

**Comment by kopnyaevtm88** [comment]
in the log / var / www / html / glpi / files / _log / php-errors.log
There are no logs for the plugin, executed the tail -f command and did synchronization, there are no logs.

**Comment by tomolimo** [comment]
could you check the result of the PHP command?
php -m

**Comment by kopnyaevtm88** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by tomolimo** [comment]
Could you post the GLPI information from the Setup > General > System tab?
The information I need are between the [code] [/code] tags?

**Comment by kopnyaevtm88** [comment]
Информация о системе, установке и конфигурации
--
[code]   GLPI 9.4.3 ( => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux stp-ubnt 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 PHP 7.1.31-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, 	intl, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline, 	session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, 	zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 172.17.21.28 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.6.16-1~exp1 	Server SQL Mode:  	Parameters: root@localhost/glpi_bd 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed APCu extension is not present CAS extension is not present Database version seems correct (5.6.16) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Server: '172.17.21.3', Port: '389', BaseDN: 'DC=it2g,DC=ru', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=ldap_sync,OU=ServiceUsers,OU=MADI,DC=it2g,DC=ru', Use TLS: none

Not active

Way of sending emails: PHP

Name: 'hd-mchs@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert}' Login: 'hd-mchs@it2g.ru' Password: Yes Name: 'hd@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'hd@it2g.ru' Password: Yes Name: 'hd-ampp@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'hd-ampp@it2g.ru' Password: Yes Name: 'sdclaim_avt@it2g.ru' Active: Yes 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'sdclaim_avt@it2g.ru' Password: Yes Name: 'odpu@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'odpu@it2g.ru' Password: Yes Name: 'testbox147@gmail.com' Active: No 	Server: '{imap.gmail.com/imap/ssl/novalidate-cert}' Login: 'testbox147@gmail.com' Password: Yes Name: 'hd-avtokod@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'hd-avtokod@it2g.ru' Password: Yes Name: 'ekks-support@mos.ru' Active: No 	Server: '{owa.mos.ru/imap/ssl/novalidate-cert/notls}GLPI' Login: 'HQ\ekks-support' Password: Yes Name: 'hd-dtoiv@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/notls}' Login: 'hd-dtoiv@it2g.ru' Password: Yes Name: 'hd-112@it2g.ru' Active: No 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'hd-112@it2g.ru' Password: Yes Name: 'sdclaim_112@it2g.ru' Active: Yes 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'sdclaim_112@it2g.ru' Password: Yes Name: 'sdclaim_odpu@it2g.ru' Active: Yes 	Server: '{mail.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'sdclaim_odpu@it2g.ru' Password: Yes Name: 'test-glpi@it2g.ru' Active: Yes 	Server: '{exchange.it2g.ru/imap/ssl/novalidate-cert/notls}' Login: 'test-glpi@it2g.ru' Password: Yes

processmaker         Name: Process Maker                  Version: 3.6.5      State: Enabled 	resources            Name: Человеческие Ресурсы  Version: 2.6.3      State: Enabled
[/code]

**Comment by kopnyaevtm88** [comment]
code]
 
GLPI 9.4.3 ( => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux stp-ubnt 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64
PHP 7.1.31-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap,
	intl, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline,
	session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 172.17.21.28 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.6.16-1~exp1
	Server SQL Mode: 
	Parameters: root@localhost/glpi_bd
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
exif extension is installed
APCu extension is not present
CAS extension is not present
Database version seems correct (5.6.16) - Perfect!Database version seems correct (5.6.16) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

Libraries
 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)



SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	processmaker         Name: Process Maker                  Version: 3.6.5      State: Enabled
	resources            Name: Человеческие Ресурсы  Version: 2.6.3      State: Enabled

[/code]

**Comment by tomolimo** [comment]
another question is: which languages are installed in PM server?

**Comment by kopnyaevtm88** [comment]
english

**Comment by tomolimo** [comment]
I need a screen copy, please

**Comment by kopnyaevtm88** [comment]
![image](https://user-images.githubusercontent.com/54949945/66387056-daccd280-e9cb-11e9-94c7-5ec820e71b15.png)

**Comment by kopnyaevtm88** [comment]
maybe skype ?

**Comment by tomolimo** [comment]
and which language is defined by default in GLPI?

**Comment by kopnyaevtm88** [comment]
Russian

**Comment by tomolimo** [comment]
check this: https://github.com/tomolimo/processmaker-server/wiki/Languages#localization-internationalization-languages

**Comment by tomolimo** [comment]
I advise you to switch GLPI default language to en-GB

**Comment by kopnyaevtm88** [comment]
Change russain :

[cid:image001.png@01D57DDA.0B0AFE30]


But there is an error in the application

[cid:image002.png@01D57DDA.0B0AFE30]



С уважением,
Копняев Тимур.
kopnyaevtm@it2g.ru<mailto:kopnyaevtm@it2g.ru>
Тел. +7(968)522-78-70
Skype:timur.kopnyaev
Email:kopnyaevtm@it2g.ru
[logo]
ВНИМАНИЕ, КОНФИДЕНЦИАЛЬНО: Это электронное письмо и его вложения могут содержать конфиденциальную информацию. Любое несанкционированное использование или разглашение конфиденциальной информации запрещено. Если Вы получили это письмо по ошибке, пожалуйста, немедленно проинформируйте об этом отправителя данного электронного письма и удалите это электронное письмо и прикрепленные к нему файлы. Спасибо!

**Comment by kopnyaevtm88** [comment]
Change russain :
![image](https://user-images.githubusercontent.com/54949945/66387898-a35f2580-e9cd-11e9-9160-4babad544951.png)
But there is an error in the application
![image](https://user-images.githubusercontent.com/54949945/66387920-b245d800-e9cd-11e9-899e-843edd08ce4d.png)

**Comment by kopnyaevtm88** [comment]
Synchronization was successful, but the process is not added to the application

**Comment by tomolimo** [comment]
ok, this is one step further :)
Could you now check the task assignment you set in the process in PM designer?

**Comment by tomolimo** [comment]
one question: did you followed the wiki here: https://github.com/tomolimo/processmaker/wiki/Tutorials?

**Comment by kopnyaevtm88** [comment]
It turns out in the process you need to specify users? He swears at this?

**Comment by tomolimo** [comment]
See: https://github.com/tomolimo/processmaker/wiki/Tutorials

**Comment by kopnyaevtm88** [comment]
there was a problem with the Russian language!

thank!!!

**Comment by tomolimo** [comment]
and then is it ok now?

**Comment by tomolimo** [comment]
Seems like it is solved,
Close the issue, but feel free to re-open if not solved, or create a new one for another problem
