### ISSUE TITLE
GLPI error in synchronize task lists 

### ISSUE THREAD

**Issue by darionsr** [tomolimo/processmaker-server#18]
Hello Mr. Tomolimo,

Thanks for advance for your help.

I have GLPI 9.4.4 whit Process Maker plugin v3.6.6 in a server + other server whit Process Maker 3.3.10-community. 

I can Synchronize Process List in GLPI but I have a problem with synchronize task lists in GLPI, they return the error: "Failed operation". I have checked that English is the default language in GLPI and Process Maker.

Could you tell me what can I check? Thanks sir.

![imagen](https://user-images.githubusercontent.com/4057778/74539894-c16a0300-4f36-11ea-9160-cb07979f1edf.png)

**Comment by darionsr** [comment]
Hi Tomolimo, i had not executed the automatic action "pmuser", sorry its my fault.

**Comment by darionsr** [comment]
Sorry, I involuntarily closed ticket. 

I just want attach the php_error.log file with the error I get when I try to synchronize task list.
![imagen](https://user-images.githubusercontent.com/4057778/74672851-03e54700-51a6-11ea-9073-4e4eb59da5a7.png)

**Comment by darionsr** [comment]
Sorry, I involuntarily closed ticket.

I just want attach the php_error.log file with the error I get when I try to synchronize task list.
![imagen](https://user-images.githubusercontent.com/4057778/74673078-73f3cd00-51a6-11ea-8abf-f8d285323e1c.png)

**Comment by tomolimo** [comment]
Hello @darionsr 
Sorry for being late to answer, but I'm currently out of office... and have little access to my emails.
Could you post the steps to reproduce the issue?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue as there is no answer!
Feel free to re-open with answers.
