### ISSUE TITLE
Error in participated folder

### ISSUE THREAD

**Issue by Ammar204** [tomolimo/processmaker-server#19]
hello, I`m using processmaker 3.4.2, everything is working fine but there is a error when I open my participated folder
![Capture](https://user-images.githubusercontent.com/49533389/79304443-ca615b80-7f0a-11ea-9a0e-5620aceeae34.PNG)

**Comment by tomolimo** [comment]
Hello @Ammar204 
Could you post the version of the PM server you are using?
![image](https://user-images.githubusercontent.com/7569958/79460269-dcb7c400-7ff4-11ea-9f0a-d65f584dd993.png)

Thank you,
Regards,
Tomolimo

**Comment by Ammar204** [comment]
hello @tomolimo 
![Untitled](https://user-images.githubusercontent.com/49533389/79460818-cd457480-800e-11ea-9c4e-cb442218db55.png)

**Comment by tomolimo** [comment]
Hello @Ammar204 

I'm sorry to tell you that you are not using the right version, see note 1 here: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation

Current version that is maintained by us is 3.3.0-community-RE-1.7
 
Thank you
Regards,
Tomolimo

**Comment by Ammar204** [comment]
sir, now what is the solution of this? and how can i update my process maker from command line?

**Comment by tomolimo** [comment]
Hello @Ammar204 
I don't think it is possible to downgrade your current version to the correct one.
I think you have to re-install the correct version from scratch.
Thank you
Regards,
Tomolimo

**Comment by Ammar204** [comment]
okay, thanks for your response :)
