### ISSUE TITLE
No access since User/Groups synchronisation with GLPI

### ISSUE THREAD

**Issue by cridiantos** [tomolimo/processmaker-server#21]
Hello,

I'm just starting with PM as I need this with GLPI.
PM has been installed and setup... with the problem of expired admin account that I've found how solve.
Then the plugin has been configured.
Then I started to synchronize User/Groups  from GLPI... following that, my admin account to access to PM became "invald".
I set it to "ACTIVE" through the database but it's not effective and I don't find any clue !

Hope you can help me.

Regards

**Comment by tomolimo** [comment]
Hello @cridiantos 
Yes, this can be a problem when in GLPI there is an admin account that will rewrite the password and status of the PM admin account.
That's why I usually advise to create a new admin (or to rename it before any user synchro).

Try the following queries (in your favorite mySQL client), they will reset the admin account to default values like admin/admin:
```
REPLACE INTO `users` (`USR_UID`, `USR_USERNAME`, `USR_PASSWORD`, `USR_FIRSTNAME`, `USR_LASTNAME`, `USR_EMAIL`, `USR_DUE_DATE`, `USR_CREATE_DATE`, `USR_UPDATE_DATE`, `USR_STATUS`, `USR_STATUS_ID`, `USR_COUNTRY`, `USR_CITY`, `USR_LOCATION`, `USR_ADDRESS`, `USR_PHONE`, `USR_FAX`, `USR_CELLULAR`, `USR_ZIP_CODE`, `DEP_UID`, `USR_POSITION`, `USR_RESUME`, `USR_BIRTHDAY`, `USR_ROLE`, `USR_REPORTS_TO`, `USR_REPLACED_BY`, `USR_UX`, `USR_COST_BY_HOUR`, `USR_UNIT_COST`, `USR_PMDRIVE_FOLDER_UID`, `USR_BOOKMARK_START_CASES`, `USR_TIME_ZONE`, `USR_DEFAULT_LANG`, `USR_LAST_LOGIN`) VALUES ('00000000000000000000000000000001', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'Administrator', 'admin', 'admin@processmaker.com', '2022-01-28', '1999-11-30 00:00:00', '2021-09-08 16:48:51', 'ACTIVE', 1, 'US', 'FL', 'MMK', '', '', '1-305-402-0282', '1-305-675-1400', '', '', 'Administrator', '', '1999-02-25', 'PROCESSMAKER_ADMIN', '', '', 'NORMAL', 0.00, '', '', NULL, '', '', '2021-09-08 16:48:51');
```

and

```
REPLACE INTO `rbac_users` (`USR_UID`, `USR_USERNAME`, `USR_PASSWORD`, `USR_FIRSTNAME`, `USR_LASTNAME`, `USR_EMAIL`, `USR_DUE_DATE`, `USR_CREATE_DATE`, `USR_UPDATE_DATE`, `USR_STATUS`, `USR_AUTH_TYPE`, `UID_AUTH_SOURCE`, `USR_AUTH_USER_DN`, `USR_AUTH_SUPERVISOR_DN`) VALUES ('00000000000000000000000000000001', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'Administrator', 'admin', 'admin@processmaker.com', '2022-01-28', '2007-08-03 12:24:36', '2008-02-13 07:24:07', 1, 'MYSQL', '00000000000000000000000000000000', '', '');
```

And don't forget to change the login to something like pm_admin/pm_admin (for exemple).

Thank you,
Regards,
Tomolimo

**Comment by cridiantos** [comment]
It works ! 
Thank you for the solution and your work !

Regards

**Comment by tomolimo** [comment]
You're welcome
