### ISSUE TITLE
PHP Fatal error:  Class 'G' not found in /opt/processmaker/workflow/public_html/sysGeneric.php on line 274

### ISSUE THREAD

**Issue by oshkurin** [tomolimo/processmaker-server#23]
Hi!

I can't find info how to resolve this issue, sorry. 

I've downloaded https://github.com/tomolimo/processmaker-server/archive/refs/tags/3.3.0-RE-1.10.tar.gz and ungzip it to /opt/processmaker. 

[root@pm opt]# cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)

[root@pm opt]# php -v
PHP 5.6.40 (cli) (built: Jan 12 2019 13:11:15) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

BTW, stack with php 7.1 error same.

[root@pm opt]# rpm -qa | grep php
php56w-common-5.6.40-1.w7.x86_64
php56w-xml-5.6.40-1.w7.x86_64
php56w-devel-5.6.40-1.w7.x86_64
php56w-mbstring-5.6.40-1.w7.x86_64
php56w-soap-5.6.40-1.w7.x86_64
php56w-cli-5.6.40-1.w7.x86_64
php56w-process-5.6.40-1.w7.x86_64
php56w-pear-1.10.4-1.w7.noarch
php56w-pecl-apcu-4.0.11-2.w7.x86_64
php56w-5.6.40-1.w7.x86_64
php56w-mcrypt-5.6.40-1.w7.x86_64
php56w-gd-5.6.40-1.w7.x86_64
php56w-pdo-5.6.40-1.w7.x86_64
php56w-mysqlnd-5.6.40-1.w7.x86_64
php56w-ldap-5.6.40-1.w7.x86_64

[root@pm opt]# mysql -V
mysql  Ver 14.14 Distrib 5.6.51, for Linux (x86_64) using  EditLine wrapper

[root@pm opt]# httpd -V
Server version: Apache/2.4.6 (CentOS)
Server built:   May 30 2023 14:01:11
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

[root@pm opt]# cat /etc/httpd/conf.d/pmos.conf 
#  NameVirtualHost 10.30.7.38
#  processmaker virtual host
  <VirtualHost 10.30.7.38>
    ServerName "pm.mof.local"
    DocumentRoot /opt/processmaker/workflow/public_html
    DirectoryIndex index.html index.php
    <Directory  "/opt/processmaker/workflow/public_html">
       AddDefaultCharset UTF-8
       AllowOverRide none
       Options FollowSymlinks
       Require all granted
       RewriteEngine on
       RewriteRule ^.*/(.*)$ sysGeneric.php [NC,L]
       ExpiresActive On
       ExpiresDefault "access plus 1 day"
       ExpiresByType image/gif "access plus 1 day"
       ExpiresByType image/png "access plus 1 day"
       ExpiresByType image/jpg "access plus 1 day"
       ExpiresByType text/css "access plus 1 day"
       ExpiresByType text/javascript "access plus 1 day"
       AddOutputFilterByType DEFLATE text/html
    </Directory>
  </VirtualHost>

I wiil appreciate any  help.
Thank you!

**Comment by tomolimo** [comment]
Hello @oshkurin 
Did you follow the wiki here https://github.com/tomolimo/processmaker-server/wiki?
I think you have an issue with the RewriteRule, see https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules
Thank you,
Regards,
Tomolimo

**Comment by oshkurin** [comment]
Tomolimo, thank you very much!

Proceemaker server working and acceprable.
