### ISSUE TITLE
WHITE PAGE PROBLEM WITH ACTIVATION OF processmaker-5.0.3 ON GLPI 10

### ISSUE THREAD

**Issue by issouf-fofana** [tomolimo/processmaker-server#28]
hi everyone please help me i just installed glpi 10 on my computer and i downloaded the processmaker-5.0.3 , i configure it to have access to my glpi interface , i manage to install it , after the installation if i activate it all my page becomes white ,   please help me. here are the captures
![Arc 2024-05-23 12_53_02](https://github.com/tomolimo/processmaker-server/assets/141040978/1d783048-5b2e-4ed2-87f2-8dc4a13b5290)

when I activate the page, it goes blank here's the capture too 
![Arc 2024-05-23 12_55_42](https://github.com/tomolimo/processmaker-server/assets/141040978/71dcfd90-7826-4582-8e90-9b14a8c956e8)

**Comment by issouf-fofana** [comment]
quelqu'un pour m'aider svp

**Comment by tomolimo** [comment]
Hello @nonymous01 
Could you give the ProcessMaker server version you've installed?
See: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check#system-information
Thank you,
Regard,
Tomolimo

**Comment by DZbox** [comment]
> Hello @nonymous01 Could you give the ProcessMaker server version you've installed? See: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check#system-information Thank you, Regard, Tomolimo

Hello @tomolimo 
Same issue
Server is 3.3.0-community-RE-2.5
Plugin is 5.0.3

**Comment by DZbox** [comment]
But, GLPI becomes blank before PM plugin is configured. So GLPI doesn't know about the PM server yet

```
Uncaught Exception Error: Undefined constant "SOAP_1_2" in /glpi/plugins/processmaker/inc/processmaker.class.php at line 216
  Backtrace :
  ...ins/processmaker/inc/processmaker.class.php:257 PluginProcessmakerProcessmaker->openSoap()
  plugins/processmaker/hook.php:337                  PluginProcessmakerProcessmaker->login()
  src/Plugin.php:1696                                plugin_processmaker_post_init()
  src/Plugin.php:276                                 Plugin::doHook()
  inc/includes.php:98                                Plugin->init()
  front/plugin.php:36                                include()
  public/index.php:82                                require()
```

**Comment by DZbox** [comment]
Solved by php-soap installation

**Comment by tomolimo** [comment]
Hello,
You may refer to the requirements needed by the plugin: https://github.com/tomolimo/processmaker/wiki/Requirements
Thank you
Regards,
Tomolimo
