### ISSUE TITLE
designer impossible to drag and drop 

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker-server#3]
Hello, I have freshly installed processmaker Release 3.0.1.8-RE-1.3., but I can't create process in designer

image
![image](https://cloud.githubusercontent.com/assets/15144026/25649854/1bef5288-2fd9-11e7-9800-b92042a28fc6.png)

I noted in script src is /js/maborak/core/maborak.loader.js"></script>

I don't have this folder in process maker folder

**Comment by tomolimo** [comment]
Hello,
You must have it there: PROCESSMAKER_FOLDER_INSTALLATION\gulliver\js\maborak\core\maborak.loader.js

ProcessMaker is doing URL rewrite in app.php file, that's why you don't have it where you were looking for.

But to come-back to your issue, could you explain what you are doing exactly for installation?
Did you follow step by step the wiki?
Did you get any error during installation?
And last but not least: what is your configuration (OS, web server, PHP, mySQL, browser, ...)?

On my side, I've tested a fresh new install from scratch, and I can create new prcesses:
![image](https://cloud.githubusercontent.com/assets/7569958/25650009/354f0c0e-2fda-11e7-8cde-6b1723670c92.png)

thank you,
regards,
Tomolimo

**Comment by satyan01** [comment]
But to come-back to your issue, could you explain what you are doing exactly for installation?
Did you follow step by step the wiki? Yes
Did you get any error during installation? No
And last but not least: what is your configuration (OS, web server, PHP, mySQL, browser, ...)?
windows server 2012 R2, IIS, php 5.6.19, mariadb 10.1, firefox

**Comment by satyan01** [comment]
When I drag and drop something it stays blank

**Comment by tomolimo** [comment]
To compare: here is my config:
on my PC: Windows 7, IIS, PHP 5.6.30, FF, Chrome, and IE10, MySQL 5.7.17
on the servers: Windows 2012-R2, IIS, PHP 5.6.26, MySQL 5.7.17

What is your configuration in IIS? 
Check in Advanced settings:
![image](https://cloud.githubusercontent.com/assets/7569958/25650435/250449ba-2fdd-11e7-8257-a732de4f497c.png)

Check also in Application pool the setting of the pool:
![image](https://cloud.githubusercontent.com/assets/7569958/25650493/86cef938-2fdd-11e7-9e5a-a925478898e0.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25650578/40190bf4-2fde-11e7-92b9-10697d73d4c6.png)
![image](https://cloud.githubusercontent.com/assets/15144026/25650588/4d23f3cc-2fde-11e7-91b2-58c1f57d3ee1.png)
![image](https://cloud.githubusercontent.com/assets/15144026/25650595/56816fe4-2fde-11e7-83a9-08d50b74bb0e.png)

**Comment by tomolimo** [comment]
Try changing 'identity' of the application pool from 'ApplicationPoolIdentity' to 'LocalSystem'

**Comment by satyan01** [comment]
same result

**Comment by tomolimo** [comment]
Could check that localsystem account has full access to the complete folder of processmaker?

**Comment by tomolimo** [comment]
to compare, here are the settings of my application pool:
![image](https://cloud.githubusercontent.com/assets/7569958/25651049/2b2d15de-2fe1-11e7-889c-996a01e10321.png)

**Comment by tomolimo** [comment]
And what are the 'Advanced settings' of the web site itself?
![image](https://cloud.githubusercontent.com/assets/7569958/25651254/5b495510-2fe2-11e7-9d76-59c1afd6a347.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25651491/a879571c-2fe3-11e7-9693-7d15c5e65c05.png)

**Comment by tomolimo** [comment]
Physical path is missing the end :)

**Comment by satyan01** [comment]
C:\inetpub\wwwroot\processmaker\workflow\public_html

**Comment by tomolimo** [comment]
did you ensure that LocalSystem has full rights on the pm folders?

**Comment by satyan01** [comment]
yes full rights

**Comment by tomolimo** [comment]
Did you try doing a full copy of my settings?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25651945/ffc8d130-2fe5-11e7-9b9e-6e3f95c33c34.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25651954/1352b0f4-2fe6-11e7-815e-a2c354a94537.png)

**Comment by tomolimo** [comment]
ok, good, so did you try doing a full copy of my settings?

**Comment by satyan01** [comment]
yes

**Comment by tomolimo** [comment]
Could you go to PHP Manager and give me the phpinfo()?
![image](https://cloud.githubusercontent.com/assets/7569958/25652213/6b61f308-2fe7-11e7-8c95-4b7c7da7805f.png)
![image](https://cloud.githubusercontent.com/assets/7569958/25652232/80f3de3e-2fe7-11e7-885b-f25c5f16d0a2.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25652278/adabde36-2fe7-11e7-9de9-edf59310142e.png)

**Comment by satyan01** [comment]
all content ?

**Comment by tomolimo** [comment]
yes, you may delete some if you want, or send it to my private email

**Comment by satyan01** [comment]
PHP Version 5.6.19 
System  Windows NT UNGSRVGVA118 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586  
Build Date  Mar 2 2016 19:59:43  
Compiler  MSVC11 (Visual C++ 2012)  
Architecture  x86  
Configure Command  cscript /nologo configure.js "--enable-snapshot-build" "--enable-debug-pack" "--disable-zts" "--disable-isapi" "--disable-nsapi" "--without-mssql" "--without-pdo-mssql" "--without-pi3web" "--with-pdo-oci=c:\php-sdk\oracle\x86\instantclient_12_1\sdk,shared" "--with-oci8-12c=c:\php-sdk\oracle\x86\instantclient_12_1\sdk,shared" "--with-enchant=shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--with-mcrypt=static" "--without-analyzer" "--with-pgo"  
Server API  CGI/FastCGI  
Virtual Directory Support  disabled  
Configuration File (php.ini) Path  C:\Windows  
Loaded Configuration File  E:\webserver\php5\php.ini  
Scan this dir for additional .ini files  (none)  
Additional .ini files parsed  (none)  
PHP API  20131106  
PHP Extension  20131226  
Zend Extension  220131226  
Zend Extension Build  API220131226,NTS,VC11  
PHP Extension Build  API20131226,NTS,VC11  
Debug Build  no  
Thread Safety  disabled  
Zend Signal Handling  disabled  
Zend Memory Manager  enabled  
Zend Multibyte Support  provided by mbstring  
IPv6 Support  enabled  
DTrace Support  disabled  
Registered PHP Streams php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar 
Registered Stream Socket Transports tcp, udp, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2 
Registered Stream Filters convert.iconv.*, mcrypt.*, mdecrypt.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, zlib.*, bzip2.*

**Comment by satyan01** [comment]
what is your email please

**Comment by tomolimo** [comment]
olivierdotmoronataraymonddotcom

**Comment by satyan01** [comment]
sent to 
![image](https://cloud.githubusercontent.com/assets/15144026/25652547/098144fc-2fe9-11e7-9f41-75371ee25ddd.png)

**Comment by tomolimo** [comment]
not yet received

**Comment by tomolimo** [comment]
yes, received now, it was in my spam folder :)

**Comment by satyan01** [comment]
;-)

**Comment by tomolimo** [comment]
Could you also post the screen copies of the following settings in ProcessMaker?
![image](https://cloud.githubusercontent.com/assets/7569958/25653053/7dbbb300-2feb-11e7-97db-570ef9eca0af.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25653411/0b6ab42a-2fed-11e7-95eb-3a629eb43e61.png)
![image](https://cloud.githubusercontent.com/assets/15144026/25653423/1622108e-2fed-11e7-9297-c76c020b39c2.png)
![image](https://cloud.githubusercontent.com/assets/15144026/25653599/d6d0cb4a-2fed-11e7-8b35-7b4c85961626.png)
![image](https://cloud.githubusercontent.com/assets/15144026/25653605/e0bac55c-2fed-11e7-9e45-a47d8d180b70.png)

**Comment by tomolimo** [comment]
I think I've have found the root cause: did you check the verbs of the fastcgi handler? 
You have to check in:

![image](https://cloud.githubusercontent.com/assets/7569958/25653546/a250f8fe-2fed-11e7-88b6-1638dc827ce2.png)
and then

![image](https://cloud.githubusercontent.com/assets/7569958/25653570/c22ae806-2fed-11e7-8ec8-b939a9a2cead.png)

I remember now that the new ProcessMaker process designer is using the verb PUT which is not enabled by default

**Comment by tomolimo** [comment]
Strange that for the 'system information' you got an empty screen copy,
I get this one from my local system
![image](https://cloud.githubusercontent.com/assets/7569958/25653686/4f39c03c-2fee-11e7-9fd5-54850df4633d.png)

**Comment by satyan01** [comment]
same result

**Comment by tomolimo** [comment]
and about your 'system information' empty screen?

**Comment by satyan01** [comment]
it is empty when i select it

**Comment by tomolimo** [comment]
not normal :(

**Comment by satyan01** [comment]
same result with chrome

**Comment by tomolimo** [comment]
let's try to trace network exchanges:
on firefox, press F12 to get to debug tools

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25653920/41d59730-2fef-11e7-801e-b3ca45bd2e2c.png)

**Comment by tomolimo** [comment]
then click on the trash
and click on the 'system information' link

and you should get something like this:

![image](https://cloud.githubusercontent.com/assets/7569958/25653959/7f92838a-2fef-11e7-8598-536ca22e483e.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25653997/adbc7932-2fef-11e7-82b0-cc34836fccf0.png)

**Comment by tomolimo** [comment]
and if you look into the 'Response' tab you should get json data

**Comment by tomolimo** [comment]
like this
![image](https://cloud.githubusercontent.com/assets/7569958/25654036/dcbb9790-2fef-11e7-933c-5313433a0e57.png)

**Comment by satyan01** [comment]
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>608</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1734</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1736</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1738</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1740</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1742</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\inetpub\wwwroot\processmaker\workflow\public_html\sysGeneric.php</b> on line <b>1768</b><br />
[{"label":"ProcessMaker Ver.","value":"3.0.1.8-community","section":"Process Information"},{"label":"PMUI JS Lib. Ver.","value":"0.1.1","section":"Process Information"},{"label":"MAFE JS Lib. Ver.","value":"  master.ae2d34d","section":"Process Information"},{"label":"PM Dynaform JS Lib. Ver.","value":"  master.8610b3d","section":"Process Information"},{"label":"Upgrades\/Patches","value":"Never upgraded","section":"Process Information"},{"label":"Operating System","value":" (WINNT)","section":"System information"},{"label":"Time Zone","value":"Europe\/Paris","section":"System information"},{"label":"Web Server","value":"Microsoft-IIS\/8.5","section":"System information"},{"label":"Server Address","value":"localhost","section":"Process Information"},{"label":"Server IP Address","value":"127.0.0.1 => UNGSRVGVA118.unigestion.org","section":"System information"},{"label":"PHP Version","value":"5.6.19","section":"System information"},{"label":"Data Base","value":"MySql (Version 5.5.5-10.1.12-MariaDB)","section":"Process Information"},{"label":"Data Base Server","value":"localhost","section":"Process Information"},{"label":"Database Name","value":"unigestion","section":"Process Information"},{"label":"Available DB Engines","value":"MySql","section":"System information"},{"label":"Workspace","value":"workflow","section":"Process Information"},{"label":"Server Protocol","value":"HTTP\/1.1","section":"System information"},{"label":"Server Port","value":"8080","section":"System information"},{"label":"Server Address","value":false,"section":"System information"},{"label":"User's Browser","value":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64; rv:53.0) Gecko\/20100101 Firefox\/53.0","section":"System information"}]

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25654401/2877eaac-2ff1-11e7-88f9-b7668d8c81ed.png)

**Comment by tomolimo** [comment]
Yes!!!
very good, how did you do that?

**Comment by satyan01** [comment]
To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.in

**Comment by tomolimo** [comment]
and then what about the processes now?

**Comment by satyan01** [comment]
but it does not solved my main issue ... ssnif

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25655662/f2605a58-2ff5-11e7-9ac7-d0b1da4aee55.png)

**Comment by tomolimo** [comment]
try the network traces

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25655714/2bb1113a-2ff6-11e7-8461-73931729e1bb.png)

**Comment by satyan01** [comment]
Is there link to internet in the code ? because we have firewall and maybe a link is blocked ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25655990/561557e6-2ff7-11e7-8d39-d5f1613c6224.png)

**Comment by satyan01** [comment]
I suspect an issue from js, but I don't know how to isolate the problem

**Comment by tomolimo** [comment]
what is the version of your firefox?

**Comment by tomolimo** [comment]
> Is there link to internet in the code ? because we have firewall and maybe a link is blocked ?

normally not,

**Comment by satyan01** [comment]
53.0

**Comment by tomolimo** [comment]
47.0.1
and Chrome?

**Comment by satyan01** [comment]
50.0.2661.94

**Comment by tomolimo** [comment]
et moi 58.0.3029.96

**Comment by tomolimo** [comment]
could you try to update your Chrome ?

**Comment by satyan01** [comment]
which version ?

**Comment by satyan01** [comment]
updates are disabled by your administrator

**Comment by tomolimo** [comment]
Ok :(

**Comment by satyan01** [comment]
je ne pense pas que ca vienne du browser

**Comment by satyan01** [comment]
meme constat sur firefox, ie, chrome

**Comment by tomolimo** [comment]
version fo IE?

**Comment by satyan01** [comment]
l'installation est propre je l'ai refaite deux fois from scratch pour etre sur

**Comment by tomolimo** [comment]
then I really don't see what can happen on your site

**Comment by tomolimo** [comment]
An idea: could you try to spy network with Fiddler4? 
This is really more powerful than the network traces of the browser

**Comment by tomolimo** [comment]
An idea: could you try to spy network with Fiddler4? 
This is really more powerful than the network traces of the browser

**Comment by satyan01** [comment]
what do i do with fiddler ? it is installed

**Comment by tomolimo** [comment]
start it
start your browser
start PM URL
and go to your process list, 
and try to create a new process
you should get a very nice list of network traces and then save it, zip it, and send it to me by private email

**Comment by satyan01** [comment]
!!!!!!!!!! it works

**Comment by satyan01** [comment]
rights on c:\windows\temp

**Comment by tomolimo** [comment]
Very good!

**Comment by tomolimo** [comment]
and what's logged into C:\Windows\TEMP\processmaker.log?
could you look?

**Comment by satyan01** [comment]
2017-05-03 14:32:40 Loading Api Configuration from: C:/inetpub/wwwroot/processmaker/shared/sites\workflow\cache\api-config.php
2017-05-03 14:32:40 Serving API mode: production

**Comment by satyan01** [comment]
do you have a template to import for example ?

**Comment by tomolimo** [comment]
Yes, check here: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-use
This is not a template but a complete process you may use as a starter in PM. BUT currently not operable from within GLPI, you have to wait for the wiki :)

**Comment by satyan01** [comment]
aie 
![image](https://cloud.githubusercontent.com/assets/15144026/25660910/9b8b5232-300e-11e7-8626-417f4693e8d5.png)

**Comment by tomolimo** [comment]
please do not use a closed issue, open a new one!
