### ISSUE TITLE
login Problem to Processmaker default page 

### ISSUE THREAD

**Issue by adilbouazzaoui** [tomolimo/processmaker-server#30]
Hello Mr. Olivier,

i came across your tutorials regarding Processmaker integration with glpi,
 i tried the steps but i'm always blocked !

could you please clarify this for me:

note: i have glpi installed in a ubuntu desktop, it's already running and working fine.

Q1: can i extract the modified version of the [ProcessMaker Community Edition] next to glpi folder in the webserver folder: /var/www/html/  ? if so then how can i do that?

Q2: the other way is that i installed this version Processmaker on a separate server "Centos 7", but i'm not able to access to login page (attached screenshot)! and i'm not sure how to connect this server with glpi server!

Thank you very much in advance for your support.

**Comment by adilbouazzaoui** [comment]
quick update:
Now that i tried the steps from the beginning (installed Processmaker in a separate server): I'm getting this error when i tried to go to homepage
<img width="419" alt="error 2" src="https://github.com/user-attachments/assets/7f117a13-d2fd-4c2d-831c-2d2114006b60">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 

1. Where did you get ProcessMake server (please give the url)?
2. Did you follow the guideline that explains how to install and configure PM server? https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation

Thank you,
Regards,

Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello Tomolimo,

Thank you for the response.


  1.
Where did you get ProcessMake server (please give the url)?
this is the URL: https://github.com/tomolimo/processmaker-server/releases/tag/RE-2.5
  2.
Did you follow the guideline that explains how to install and configure PM server? https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation
yes i did follow all the steps (in the above URL) multiple times on different servers.


Now i confirm that i fixed the php issue (it was that Apache wasn't parsing php), but when i type the IP of the server i get redirected to a blank login page (even if i try on different browsers)!

[cid:5d751869-8635-41d5-9840-1e795d520b1c]


This is php version:
[cid:8cb32aa4-adc0-4f5b-97e7-06f815103735]


this is mysql version:
[cid:3a985cf5-a718-43f2-a0f9-9039cdb5fe63]


this is apache version:
[cid:4ab67ca6-3cb0-40f8-b62c-d771e62087a6]


this is the pmos.conf inside /etc/httpd/conf.d/ directory:
[cid:7d511a95-75dd-4753-bb56-c4c659a0c8d1]


and the httpd.conf file is attached.


i hope i provided all the required information, hopefully with your support i can get this fixed.



Regards

Adil Bouazzaoui



[cid:8a5a299a-1960-4287-b7c3-d52c38010a52]

**Comment by adilbouazzaoui** [comment]
<img width="954" alt="1" src="https://github.com/user-attachments/assets/8f59296f-ef61-43df-9fb6-02a9f2384e05">
<img width="371" alt="2" src="https://github.com/user-attachments/assets/6585629c-4a8e-4abe-bf02-5c6b13c20ec6">
<img width="457" alt="3" src="https://github.com/user-attachments/assets/adc4b330-7d6a-4b35-aeb9-1ad0eadb9a15">
<img width="227" alt="4" src="https://github.com/user-attachments/assets/88235ed0-426f-4916-9d5c-5ec4cabef737">
<img width="334" alt="5" src="https://github.com/user-attachments/assets/e07800af-8c08-492f-bfa1-135ccbb74ab9">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
1. your PHP version should be 7.1
2.  your FPM handle in Apache is not defined
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
refer to https://docs.cpanel.net/ea4/php/php-handlers/#fastcgi-process-manager-fpm

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
1. your PHP version should be 7.1 ==> i installed the php 7.1 and now i can see the login page, but it is not showing correctly!
2. your FPM handle in Apache is not defined ==> i checked the documentation but i don't know how to do it! can you please help on this?

**Comment by adilbouazzaoui** [comment]
![1](https://github.com/user-attachments/assets/6b14a846-e509-4ecb-8e0b-2e8c40e2de28)
<img width="327" alt="2" src="https://github.com/user-attachments/assets/d7faa96f-2a39-4528-aa69-fed830fe69a4">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
It seems now that FPM is installed :)
But did you authorized javascript in your borwser for this website?
Or you may have troubles with your browser cache...
thank you
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
yes javascript is enabled.
and i tested on different browsers.

thanks in advance

**Comment by adilbouazzaoui** [comment]
<img width="560" alt="javascript" src="https://github.com/user-attachments/assets/dab19327-c2ff-40fe-836a-2a393348c790">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
I really don't know what your problem is, but you have to check if you have all the needed PHP modules
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Could you check if you have any error messages in the php-error log file?

**Comment by adilbouazzaoui** [comment]
the good news is that i'm able to bypass login page by clicking on next....
now i'm able to login with admin user, the designer and dashboard look fine to me, however the Admin page is not working properly!

<img width="958" alt="1" src="https://github.com/user-attachments/assets/8301fa80-0d90-4cd2-9814-9788c3b625ac">
<img width="598" alt="2" src="https://github.com/user-attachments/assets/fddd6f0f-1ae1-45fc-a84e-8a93cbb02e3d">
<img width="955" alt="3" src="https://github.com/user-attachments/assets/0ce21651-1ebf-4485-9ccf-270a0477ca93">

**Comment by tomolimo** [comment]
I'have moved to the right repo your issue, as it is not related to the plugin, but to the server

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
I fear that you have not respected the folder rights that must be given to the "shared" folder
Could you check that?
thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
thanks for the response.
i checked and i confirm that apache already has the rights on shared folder. please check the screenshot.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/ac73a8bd-4341-4066-9700-dc0a755cab6d">

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
good news, i'm able to use the processmaker pages normally using Firefox on Ubuntu (from glpi server).

1- now i'm this point, and i'm wondering if it's required! since i'm only using english language: https://github.com/tomolimo/processmaker/wiki/Requirements

2- i installed processmaker plugin, but when i enable it i can no longer access glpi interface!

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Which browser are you using?
I beleive that you have troubles with some browser cache...
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello again,
Could you follow all the details from the installation and configuration wikis?
If you do so I can guarantee that everything will be running correctly.
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
sure.
can you just confirm if this is required! since i'm only using english language: https://github.com/tomolimo/processmaker/wiki/Requirements

**Comment by tomolimo** [comment]
You'll need the INTL and SOAP modules like described :)

**Comment by tomolimo** [comment]
To be sure that everything is installed and configured correctly, could you post screenshots of the ProcessMaker admin pages?

**Comment by adilbouazzaoui** [comment]
here you are
<img width="467" alt="1" src="https://github.com/user-attachments/assets/c84ec906-dc3f-4483-9d85-756accc5f11f">

**Comment by adilbouazzaoui** [comment]
another issue i'm facing is that i'm not able to drag items to the free white space!
i tried different browsers with no luck!
<img width="470" alt="image" src="https://github.com/user-attachments/assets/d803b687-36e7-4bac-80f7-ebb5f6a7e0b9">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
When I see this screenshot, what I can see is that something is not installed correctly...

> here you are <img alt="1" width="467" src="https://private-user-images.githubusercontent.com/111515792/373676085-c84ec906-dc3f-4483-9d85-756accc5f11f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODMxMzMsIm5iZiI6MTcyODI4MjgzMywicGF0aCI6Ii8xMTE1MTU3OTIvMzczNjc2MDg1LWM4NGVjOTA2LWRjM2YtNDQ4My05ZDg1LTc1NmFjY2M1ZjExZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNjMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjllZGFkNWUyYzJkMjk2NmFjMWZjZjRkOTQwNjljZTQ3ZDA4ZTU4ZjkzMmVlZjNmMjE1ODIwMWE5YmRmNjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PMkY7AAAfBfHpNtyU6U6AumXthWseWDysoNBmgsyiM0">

So to help you, I need to view all the screenshots you may find in this section of the wiki (and under): https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
please find attached all the screenshots.
<img width="950" alt="1" src="https://github.com/user-attachments/assets/468d609a-33b4-4778-8031-59bf2280dde0">
<img width="954" alt="2" src="https://github.com/user-attachments/assets/50375842-6c35-4ed5-8e90-3791d1494e70">
<img width="609" alt="3" src="https://github.com/user-attachments/assets/fea10049-30b6-401f-a8fb-b25908c2251d">
<img width="518" alt="4" src="https://github.com/user-attachments/assets/ee3ea17e-4594-420e-a8ac-31399c7b1570">
<img width="539" alt="5" src="https://github.com/user-attachments/assets/89a39105-1fdb-41b0-b934-7e5fe6dcd6a8">
<img width="822" alt="6" src="https://github.com/user-attachments/assets/f2a549c6-bddb-4a47-a1c1-42a9638fa38f">
<img width="719" alt="7" src="https://github.com/user-attachments/assets/4a429b8a-8a25-4e7d-ade1-7080317a7630">
<img width="780" alt="8 1" src="https://github.com/user-attachments/assets/bc1cbbbd-01f7-43a6-aefb-a372eca1b23d">
<img width="794" alt="8 2" src="https://github.com/user-attachments/assets/d70bc753-3b03-4e8f-99ab-8dc6d80f6a7e">
<img width="789" alt="8 3" src="https://github.com/user-attachments/assets/206cbc76-12af-4e94-9e69-db900ac026f6">
<img width="780" alt="8 4" src="https://github.com/user-attachments/assets/b8c0c019-a7d9-48cc-ae13-1c624b066dc6">
<img width="781" alt="8 5" src="https://github.com/user-attachments/assets/6ccec860-c6f7-4c44-b58e-0b97388324ad">
<img width="794" alt="8 6" src="https://github.com/user-attachments/assets/2e4b494c-5cd2-4caa-b37d-b45412974ace">
<img width="785" alt="8 7" src="https://github.com/user-attachments/assets/960f2820-f87c-4afa-8fcc-e11ff2adf6f5">
<img width="785" alt="8 8" src="https://github.com/user-attachments/assets/5eb4e774-489c-496c-abe8-d624662bd704">
<img width="781" alt="8 9" src="https://github.com/user-attachments/assets/b284ad59-7d82-4be1-a97c-091c55084f4e">
<img width="782" alt="8 10" src="https://github.com/user-attachments/assets/c663fd61-190f-4ebb-859d-30547003223d">
<img width="779" alt="8 11" src="https://github.com/user-attachments/assets/cb13e489-5b7a-4575-8c01-889e789a5240">
<img width="778" alt="8 12" src="https://github.com/user-attachments/assets/f9b2ac1d-7d11-465b-af2a-708cf00b41a5">
<img width="362" alt="8 13" src="https://github.com/user-attachments/assets/fa49645c-9479-41f2-8083-55142576173e">
<img width="365" alt="8 14" src="https://github.com/user-attachments/assets/c078c9e2-4202-4c12-975f-c149717dd08f">
<img width="357" alt="8 15" src="https://github.com/user-attachments/assets/3a0e030f-c6ca-410e-8c4b-26a06243fabc">
<img width="358" alt="8 16" src="https://github.com/user-attachments/assets/b02c2c42-530a-45f9-baaf-4c2427e2c961">
<img width="362" alt="8 17" src="https://github.com/user-attachments/assets/809ce9a1-0556-485a-962d-3feae7aec452">
<img width="358" alt="8 18" src="https://github.com/user-attachments/assets/3b7ba3f3-0e61-4c72-86b2-8d045336e61f">
<img width="361" alt="8 19" src="https://github.com/user-attachments/assets/28908f08-2ce5-4232-a921-12707d0aa6e6">
<img width="359" alt="8 20" src="https://github.com/user-attachments/assets/a8b60c62-22c7-456f-943c-d4a4e2a1e79c">
<img width="364" alt="8 21" src="https://github.com/user-attachments/assets/20e96d67-22af-40cc-8d42-e349eb505175">

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
i hope i provided all the required screenshot.
did you have the chance to take a look at it?

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Could you try to clear the caches like proposed on this screen?
![image](https://github.com/user-attachments/assets/d4f868b9-64b4-43db-aa13-1a492c17319a)
Check the checkboxes, and click on 'Clear' button.
Thank you
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
i checked the 3 boxes and cleared the cache, but still not able to use the designer!

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
INTL and SOAP PHP modules are missing like requested in the requirements...
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
> Hello @tomolimo i checked the 3 boxes and cleared the cache, but still not able to use the designer!

To troubleshoot this issue: have a look in the browser console, if there is any error messages

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
INTL and SOAP are already installed, please check screenshots:
<img width="275" alt="1" src="https://github.com/user-attachments/assets/4f1c0d9a-4fb0-4cb8-b6be-ed1f1c7d29c3">

**Comment by adilbouazzaoui** [comment]
> > Hello @tomolimo i checked the 3 boxes and cleared the cache, but still not able to use the designer!
> 
> To troubleshoot this issue: have a look in the browser console, if there is any error messages

please check attached screenshots:

**Comment by adilbouazzaoui** [comment]
![2](https://github.com/user-attachments/assets/0ebbb4cb-01f1-4270-8ca8-49835eff010a)
![4](https://github.com/user-attachments/assets/c7c9e7e2-6da7-4541-9c15-b98ebf1824b2)

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
As long as your installation will not be done/configured correctly, you'll get a lot of errors everywhere...
So, please, let's start again: logout from PM server, and open the browwser console, purge the logs, and try to refresh the login page: do you see errors in the browser console?
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
thank you for the quick response.
i tried and i don't see any error:
![1](https://github.com/user-attachments/assets/8a5da47c-0dd1-46da-b4e8-02f8f150d4bc)

**Comment by tomolimo** [comment]
Could you also provide a screen copy of the login screen?

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
here you are
<img width="677" alt="1" src="https://github.com/user-attachments/assets/6a7c71e9-5dab-48d3-84aa-939913159ea3">

**Comment by tomolimo** [comment]
Thank you,
Could you continue the login process keeping the browser console open to see if any errors are generated?
Could you also check if there is any PHP errors?

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
i tried and i didn't get any php error (see attached empty php log).
i'm attaching also the console error
<img width="314" alt="1" src="https://github.com/user-attachments/assets/20edf3e4-b21c-491c-939c-425687206c1d">
<img width="700" alt="2" src="https://github.com/user-attachments/assets/979c7a76-978f-444a-940a-ef98f3dacb47">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
I can see from this screenshot that PHP error log is here: /var/log/php-fpm/www-error.log, and not in /var/log/php_errors.log
![image](https://github.com/user-attachments/assets/cbac22a3-6d5f-405a-a47f-adcc8a58dba8)

Could you look into /var/log/php-fpm/www-error.log?
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
thank you for the clarification.
indeed the php log is showing some errors, and when i tried to access login page today i got these errors:
<img width="850" alt="1" src="https://github.com/user-attachments/assets/c1a91c69-8500-46ec-9f66-c2d5bc706b70">

**Comment by tomolimo** [comment]
what's the URL for these errors?

**Comment by adilbouazzaoui** [comment]
> what's the URL for these errors?

login page

**Comment by tomolimo** [comment]
yes, but I need the URL not the title of the page: you may blur the hostname.

**Comment by adilbouazzaoui** [comment]
hello @tomolimo
the good news is that i reinstalled a new server and everything is working fine now, seems that it was an issue with the installation. 
we also updated GLPI to 10.0.15 and now the i'm able to install the plugin.
Thank you for the support.
