### ISSUE TITLE
Can't see task list

### ISSUE THREAD

**Issue by softptmesvcuellar** [tomolimo/processmaker-server#32]
I have created the first tutorial and synced the process list in glpi, but cant sync the tasks on the process.
Pm api seems to not see created tasks.
No php errors on neither side.
ProcessMaker server is using its own php-fpm.
![pmconfig](https://github.com/user-attachments/assets/875b94d5-1b1c-4561-870c-d18077ba19fa)
![pmpluginconfig](https://github.com/user-attachments/assets/8f6e7ecb-28e2-4569-8ded-206d9eb530b1)
![takslist](https://github.com/user-attachments/assets/7f9836b7-c8a6-4537-a37b-ee68b1451b76)
![tutorial1](https://github.com/user-attachments/assets/70eaf5e6-62ae-428b-852e-2fb7ebd291de)
![tasklist2](https://github.com/user-attachments/assets/e583806b-2385-4eb4-a2c6-62198b76dbeb)

**Comment by tomolimo** [comment]
Hello @softptmesvcuellar 
Could you check that there is a defined path to file here:
![image](https://github.com/user-attachments/assets/fafb8f3a-c51a-4b46-a408-fdfe9655ec4e)
?
And could you check if there are errors in the error_log file?
If there is no filepath, then could you add one in the php.ini config file and then re-do a test and check again the error_log file?

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @softptmesvcuellar 
I think that there is something that is not correctly configured about default language in GLPI vs language in PM server.

Could you confirm that:

1. In PM server, the Intl PHP module is correctly installed 
![image](https://github.com/user-attachments/assets/6ca2ac4d-335c-4794-a1ea-7ce91e268b92)
2. Confirm that dropdown translation is activated in GLPI: see: https://github.com/tomolimo/processmaker/wiki/Requirements#activation-of-the-dropdown-translations 
![image](https://github.com/user-attachments/assets/4a58b961-f2f8-4d23-9119-73ad299b9a7a)

3. What's GLPI default language, and what's PM server default language? Post screenshot like below
![image](https://github.com/user-attachments/assets/cee94189-9763-4646-8038-77dcc9b6c08c)

Thank you
Regards,
Tomolimo

**Comment by softptmesvcuellar** [comment]
Fixed changing default language to English
