### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker-server#4]
aie 
![image](https://cloud.githubusercontent.com/assets/15144026/25660910/9b8b5232-300e-11e7-8626-417f4693e8d5.png)

**Comment by tomolimo** [comment]
Yes?
but what did you do?

**Comment by satyan01** [comment]
nothing

**Comment by satyan01** [comment]
I started to create a process and error 500

**Comment by tomolimo** [comment]
Try what is proposed in the page: 
![image](https://cloud.githubusercontent.com/assets/7569958/25661206/edb74da8-300f-11e7-855d-8f029374fa39.png)

**Comment by tomolimo** [comment]
Any news?

**Comment by satyan01** [comment]
it works without doing anything
