### ISSUE TITLE
tasks will not synchronize in GLPI

### ISSUE THREAD

**Issue by sosfc** [tomolimo/processmaker-server#6]
Hi
I have set up a GLPI 9.2.1 on debian 8 Jessie (PHP 5.6.33)
My PM server is installed as said in your documentation (debian 8 Jessie; php 5.6.33, pm 3.1.0.8-Community-RE-1.8 downloaded on you github).
I could configure the 3.2.8 plugin in GLPI.
I followed tutorial 1 but cannot have tasks synchronized in GLPI. When I click on the "Synchronize tasks" in GLPI, nothing happens

In my logs I have (GLPI server) : 
2018-04-02 15:28:51 [2@test]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  plugins/processmaker/inc/process.class.php:77      
  plugins/processmaker/front/process.form.php:20     PluginProcessmakerProcess->refreshTasks()

in php logs (pm server), I only have one line (but many times) : 
[02-Apr-2018 15:28:22 America/Martinique] PHP Warning:  Creating default object from empty value in /opt/processmaker/workflow/engine/classes/class.wsBase.php on line 5940

Have I forgotten something ?
Thanks,
Regards

**Comment by tomolimo** [comment]
Hello,
Could you also post the GLPI configuration and Processmaker plugin configuration?
It seems like a trouble in the mapping of GLPI languages in the plugin. I'm going to test this particular point.

Also, this can be linked to https://github.com/tomolimo/processmaker/issues/38

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Could you tell me the default language you have defined in GLPI and in PM server?
I think this is root cause of the issue when those languages are different.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Could you copy/paste the following screencopy?
![image](https://user-images.githubusercontent.com/7569958/38236707-536b2256-3725-11e8-8f20-9eec27aace14.png)

I need to know which languages are installed in PM server.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
See solution here: https://github.com/tomolimo/processmaker/issues/38#issuecomment-378211804
Thank you
Regards,
Tomolimo
