### ISSUE TITLE
Error when creating a glpi request

### ISSUE THREAD

**Issue by sosfc** [tomolimo/processmaker-server#7]
Hi Tomolimo,
I tried to follow you tutorial 2 but whet I try to create the ticket, I have the following  error 

Erreur à la création du cas !
You tried to start a new case without send the USER UID or TASK UID! (100)

The ticket cannot be created
Have I done something wrong ?
Thanks

**Comment by tomolimo** [comment]
Hello @sosfc 
Did you, in the process design, assigned someone (or a group) to the starting task?
Regards,
Tomolimo

**Comment by sosfc** [comment]
Hello, Tomolimo,
In GLPI I did set the autorizations to the profile
in PM, I did set the Assignment Rules for tasks 1 and 2

**Comment by tomolimo** [comment]
Hello @sosfc 

Could you provide GLPI configuration, PM plugin configuration and PM server configuration?
Could you provide GLPI complete (=complete browser window) screenshots of the case start (when the error occurs)?
Could you provide log file content?
And anything else that can help me reproduce the issue.

Thank you,
Regards,
Tomolimo

**Comment by sosfc** [comment]
Hello,
Thanks for youfast answer. Here are the configurations of PM and GLPI
[glpi_pm_tuto2_error.pdf](https://github.com/tomolimo/processmaker-server/files/1883639/glpi_pm_tuto2_error.pdf)
Thanks,
Regards
Fernand

**Comment by sosfc** [comment]
Hi,
Here are the log of the PM server :
[06-Apr-2018 06:39:55 America/Martinique] PHP Warning:  Creating default object from empty value in /opt/processmaker/workflow/engine/classes/class.wsBase.php on line 5940
[06-Apr-2018 06:47:54 America/Martinique] PHP Notice:  Trying to get property of non-object in /opt/processmaker/workflow/engine/methods/services/soap2.php on line 756
[06-Apr-2018 06:47:54 America/Martinique] PHP Notice:  Undefined property: wsResponse::$caseId in /opt/processmaker/workflow/engine/methods/services/soap2.php on line 780
[06-Apr-2018 06:49:49 America/Martinique] PHP Notice:  Trying to get property of non-object in /opt/processmaker/workflow/engine/methods/services/soap2.php on line 756
[06-Apr-2018 06:49:49 America/Martinique] PHP Notice:  Undefined property: wsResponse::$caseId in /opt/processmaker/workflow/engine/methods/services/soap2.php on line 780

No log in GLPI server
Regards
Fernand

**Comment by tomolimo** [comment]
And the task list of the process?
thank you
regards,
Tomolimo

**Comment by sosfc** [comment]
[glpi_pm_tuto2_error_2.pdf](https://github.com/tomolimo/processmaker-server/files/1883921/glpi_pm_tuto2_error_2.pdf)
Here is the tasks list in process 2

**Comment by tomolimo** [comment]
and the steps (in the tasks), and the assignment rules?
thank you

**Comment by tomolimo** [comment]
could you also post the GLPI logs?
thank you

**Comment by sosfc** [comment]
Hi
Here are the logs in php_error.log for glpi server (it does not seem to be concerned...)
2018-04-05 15:57:41 [2@test]
  *** PHP Notice(8): Undefined index: list
  Backtrace :
  inc/commontreedropdown.class.php:527               
  inc/commontreedropdown.class.php:99                CommonTreeDropdown->showChildren()
  inc/commonglpi.class.php:482                       CommonTreeDropdown::displayTabContentForItem()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
2018-04-05 16:10:56 [2@test]
  *** PHP Notice(8): Undefined index: list
  Backtrace :
  inc/commontreedropdown.class.php:527               
  inc/commontreedropdown.class.php:99                CommonTreeDropdown->showChildren()
  inc/commonglpi.class.php:482                       CommonTreeDropdown::displayTabContentForItem()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
2018-04-05 16:58:50 [2@test]
  *** PHP Notice(8): Undefined index: entity_restrict
  Backtrace :
  ajax/dropdownTicketCategories.php:45

Attached is the process file and the screen copies 
[glpi_pm_tuto2_error_3.pdf](https://github.com/tomolimo/processmaker-server/files/1884053/glpi_pm_tuto2_error_3.pdf)
[Tutorial_2.pmx.zip](https://github.com/tomolimo/processmaker-server/files/1884055/Tutorial_2.pmx.zip)

**Comment by tomolimo** [comment]
there is no other errors?
this is surprising :)
thank you
I'm looking at all material you posted.
regards,
Tomolimo

**Comment by tomolimo** [comment]
on my PC: the process starts:
![image](https://user-images.githubusercontent.com/7569958/38423527-75592224-39ae-11e8-8866-eb8d5971b695.png)
Of course, I've been forced to change the task assignments, as I don't have the same groups on my config.
Could you cross-check that the user logged in GLPI belongs to the GLPI_PM group?

**Comment by tomolimo** [comment]
Which GLPI version was it?

**Comment by sosfc** [comment]
GLPI 9.2.1

**Comment by tomolimo** [comment]
I made my test with the 9.1.2, so I'll try again

**Comment by sosfc** [comment]
Hi Tomolimo
I confirm that it works with GLPI 9.1.2 but not with GLPI 9.2.1
Regards
Fernand

**Comment by tomolimo** [comment]
Hello @sosfc 
It seems there is an issue with the 9.2.1 version.
I'm going to fix it.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @sosfc,

Could you tell me which language you are using in PM server? And in GLPI (I mean the default GLPI language, not your own one)? Thank you

And could you give me back the result of this SQL query (From WF_WORKFLOW Database)?
`SELECT TASK.TAS_UID, TASK.TAS_START, CONTENT.CON_LANG, CONTENT.CON_CATEGORY, CONTENT.CON_VALUE FROM TASK
                        INNER JOIN CONTENT ON CONTENT.CON_ID=TASK.TAS_UID
                        WHERE TASK.TAS_TYPE = 'NORMAL' AND TASK.PRO_UID = '3576191895ac610c021c750006278346' AND CONTENT.CON_CATEGORY IN ('TAS_TITLE', 'TAS_DESCRIPTION')  ;`

Thank you,
Regards,
Tomolimo

**Comment by sosfc** [comment]
Hello Tomolimo,
I use French in PM and GLPI
There is the result of the sql query :: 
MariaDB [wf_workflow]> SELECT TASK.TAS_UID, TASK.TAS_START, CONTENT.CON_LANG, CONTENT.CON_CATEGORY, CONTENT.CON_VALUE FROM TASK INNER JOIN CONTENT ON CONTENT.CON_ID=TASK.TAS_UID WHERE TASK.TAS_TYPE = 'NORMAL' AND TASK.PRO_UID = '3576191895ac610c021c750006278346' AND CONTENT.CON_CATEGORY IN ('TAS_TITLE', 'TAS_DESCRIPTION') ;
+----------------------------------+-----------+----------+-----------------+-----------+
| TAS_UID                          | TAS_START | CON_LANG | CON_CATEGORY    | CON_VALUE |
+----------------------------------+-----------+----------+-----------------+-----------+
| 5902221145ac612c9949a88077652698 | FALSE     | en       | TAS_DESCRIPTION |           |
| 5902221145ac612c9949a88077652698 | FALSE     | en       | TAS_TITLE       | Tâche 2   |
| 5902221145ac612c9949a88077652698 | FALSE     | fr       | TAS_DESCRIPTION |           |
| 5902221145ac612c9949a88077652698 | FALSE     | fr       | TAS_TITLE       | Tâche 2   |
| 9871564065ac610c0416182043031370 | TRUE      | en       | TAS_DESCRIPTION |           |
| 9871564065ac610c0416182043031370 | TRUE      | en       | TAS_TITLE       | Tâche 1   |
| 9871564065ac610c0416182043031370 | TRUE      | fr       | TAS_DESCRIPTION |           |
| 9871564065ac610c0416182043031370 | TRUE      | fr       | TAS_TITLE       | Tâche 1   |
+----------------------------------+-----------+----------+-----------------+-----------+
8 rows in set (0.00 sec)

MariaDB [wf_workflow]>

Regards
Fernand

**Comment by tomolimo** [comment]
Hello @sosfc,
The issue I though, was not linked to yours: I had a problem with the languages it seems you don't have.
Could you copy/paste a screen copy of the users in GLPI_PM group in PM server? Like following:
![image](https://user-images.githubusercontent.com/7569958/38494642-f8f61822-3bf6-11e8-9fa2-8356a04055ba.png)
And:
![image](https://user-images.githubusercontent.com/7569958/38494660-0ae570e6-3bf7-11e8-8822-ad3d41540ba1.png)
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello again
Just one question did you synchronized GLPI users with PM users using the automatic job?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I can see that your "post-only" user is "inactive", which means that you'll not be able to start any cases with this account...

**Comment by sosfc** [comment]
yes !
it's ok now, sorry for this mistake...

**Comment by tomolimo** [comment]
No problem,
thank you
regards,
Tomolimo
